name: Quality

on:
  push:
    branches:
      - main
      - "*-release"
      - "*-pre"
  pull_request:
    branches:
      - main
      - "*-release"
      - "*-pre"
  workflow_dispatch:

jobs:

  check_code_quality:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Setup Python environment
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6
      - name: Install pre-commit
        run: uv pip install pre-commit --system
      - name: Code quality
        run: |
          make check